# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1clrnokAOo0xrjIN03YwNcXej0NYJXD1y
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load dataset
data = pd.read_csv("data.csv")

# Features and target
X = data[['study_hours', 'sleep_hours', 'attendance', 'phone_usage']]
y = data['exam_score']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Take user input
print("Enter student details:")

study_hours = float(input("Study hours per day: "))
sleep_hours = float(input("Sleep hours: "))
attendance = float(input("Attendance (%): "))
phone_usage = float(input("Phone usage (hours): "))

# Predict
prediction = model.predict([[study_hours, sleep_hours, attendance, phone_usage]])

print(f"\nPredicted Exam Score: {prediction[0]:.2f}")